-- Контрольные запросы после заливки дампов.
-- Ожидаемые значения выверены по исходным .sql-файлам.

SET LINESIZE 200
SET PAGESIZE 100
SET FEEDBACK OFF

PROMPT === Число строк (ожидается 5228 / 182 / 1331 / 1316) ===
SELECT 'GEOMETRY' AS TABLE_NAME, COUNT(*) AS CNT, 5228 AS EXPECTED FROM GEOMETRY
UNION ALL SELECT 'GPO',   COUNT(*), 182  FROM GPO
UNION ALL SELECT 'PROBA', COUNT(*), 1331 FROM PROBA
UNION ALL SELECT 'PARAM', COUNT(*), 1316 FROM PARAM;

PROMPT
PROMPT === Кодировка: PROBA_NUM с кириллической буквой (ожидается 1) ===
SELECT COUNT(*) AS CYRILLIC_ROWS FROM PARAM WHERE PROBA_NUM = 'р112';

PROMPT
PROMPT === Связь PROBA.ID -> GPO.ID (ожидается 177 из 182) ===
SELECT COUNT(DISTINCT p.ID) AS MATCHED_POINTS
FROM PROBA p JOIN GPO g ON p.ID = g.ID;

PROMPT
PROMPT === Связь PARAM -> PROBA (ожидается 1306 проб с химией из 1331) ===
SELECT COUNT(DISTINCT a.PROBA_NUM) AS PROBES_WITH_KCL
FROM PARAM a JOIN PROBA p ON a.PROBA_NUM = p.PROBA_NUM;

PROMPT
PROMPT === Слои GEOMETRY (ожидается 182 точки и 5046 объектов подложки) ===
SELECT SUBLAYERGUID, COUNT(*) AS CNT FROM GEOMETRY GROUP BY SUBLAYERGUID ORDER BY CNT;

PROMPT
PROMPT === Пробы с конфликтующими значениями KCl (ожидается 10) ===
SELECT COUNT(*) AS CONFLICTING_PROBES FROM (
  SELECT PROBA_NUM FROM PARAM GROUP BY PROBA_NUM HAVING COUNT(*) > 1
);

PROMPT
PROMPT === Диапазоны (POWER_LAYER 0.02-4.91, VALUE 0.08-72.69, Z -449.407..-380.087) ===
SELECT MIN(POWER_LAYER) AS MIN_POWER, MAX(POWER_LAYER) AS MAX_POWER FROM PROBA;
SELECT MIN(VALUE) AS MIN_KCL, MAX(VALUE) AS MAX_KCL FROM PARAM;
SELECT MIN(Z) AS MIN_Z, MAX(Z) AS MAX_Z FROM GPO;

SET FEEDBACK ON
